area:
  config:
    - changed-files:
      - any-glob-to-any-file: '.github/**/*'
      - any-glob-to-any-file: 'packages/config/**/*'
      - any-glob-to-any-file: 'turbo.json'
      - any-glob-to-any-file: 'pnpm-lock.yaml'

'area: web':
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

'area: admin':
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

'area: droid':
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

'area: database':
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

'area: payment':
  - changed-files:
      - any-glob-to-any-file: 'packages/payment-engine/**/*'

'area: ui':
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

'area: docs':
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
